name: 'CustomSkinsManager'
main: 'ru.csm.bukkit.Skins'
version: '2.0.5'
api-version: '1.13'
author: '_Nanit_'
depend:
  - "ProtocolLib"
softdepend:
  - "Citizens"
commands:
  csm:
    description: 'Custom Skins Manager main command'
    aliases: ["skin", "skins"]
  csmskull:
    permission: 'csm.skulls'
    description: 'Custom Skins Manager skull command'
    aliases: ["skull"]
permissions:
  csm.skin.player:
    description: "Allow to setup skin from license name"
  csm.skin.url:
    description: "Allow to setup skin from url to image"
  csm.skin.menu:
    description: "Allow to open menu with users skins"
  csm.skin.reset:
    description: "Allow to reset skin to default"
  csm.skin.npc:
    description: "Allow to set skin via url for Citizens NPC's"
  csm.skin.to:
    description: "Allow to setup skins for any player"
  csm.admin:
    description: "Allow to use '/csm reload' command. More information see on spigotmc"
  csm.skulls:
    description: "Allow to use '/skull <player>' command. More information see on spigotmc"